export const GET_HOME_IMAGE_REQUEST = "GET_HOME_IMAGE_REQUEST";
export const GET_HOME_IMAGE_SUCCESS = "GET_HOME_IMAGE_SUCCESS";
export const GET_HOME_IMAGE_FAIL = "GET_HOME_IMAGE_FAIL";

export const GET_HEADER_TOP_IMAGE_REQUEST = "GET_HEADER_TOP_IMAGE_REQUEST";
export const GET_HEADER_TOP_IMAGE_SUCCESS = "GET_HEADER_TOP_IMAGE_SUCCESS";
export const GET_HEADER_TOP_IMAGE_FAIL = "GET_HEADER_TOP_IMAGE_FAIL";

export const SET_ALERT  =  "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const SET_MODE_REQUEST = "SET_MODE_REQUEST";
export const SET_MODE_SUCCESS = "SET_MODE_SUCCESS";
export const SET_MODE_FAIL = "SET_MODE_FAIL";

export const LINK = "https://fenley.herokuapp.com/api";


